// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2026-06-17, 1:09:43 p.m.
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["C:/Users/abour/repo/TripToTrip/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/abour/repo/TripToTrip/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/abour/repo/TripToTrip/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/abour/repo/TripToTrip/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/abour/repo/TripToTrip/plugins/**/*.{js,ts,mjs}","C:/Users/abour/repo/TripToTrip/composables/**/*.{js,ts,mjs}","C:/Users/abour/repo/TripToTrip/utils/**/*.{js,ts,mjs}","C:/Users/abour/repo/TripToTrip/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/abour/repo/TripToTrip/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/abour/repo/TripToTrip/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/abour/repo/TripToTrip/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;